### ISSUE TITLE
Not work and cause errors! (動かないし、エラーが発生します!)

### ISSUE THREAD

**Issue by raccy** [raccy/show-ideographic-space#7]
This package v0.1.7 dose not work and causes errors in the latest Atom.
Because Token and TokenizedLines that the package hack are different from the previous version.
So please disable it, until I release the next version that uses a different logic.

0.1.7は最新のAtomでは正常に動作せずに、いくつかのエラーを発生させます。
APIが変わってしまったのが原因です。
対応版をリリースするまでは、無効にされるようにお願いします。

**Comment by raccy** [comment]
1.0.0をリリースしました。
方式が全く違う物になったので、前の設定等は引き継がれません。
表示を変得る場合は、READMEを参照してください。

**Comment by nibushibu** [comment]
:+1:
