### ISSUE TITLE
Deprecated selector in `show-ideographic-space/styles/show-ideographic-space.less`

### ISSUE THREAD

**Issue by nibushibu** [raccy/show-ideographic-space#9]
In `show-ideographic-space/styles/show-ideographic-space.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .highlight.ideographic-space .region:after,
atom-text-editor::shadow .highlight.ideographic-space .region:after` => `atom-text-editor .highlight.ideographic-space .region:after,
atom-text-editor.editor .highlight.ideographic-space .region:after`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by raccy** [comment]
I changed selector form `::shadow` to `.editor`. But my package didn't work in v1.29.x (-д-;
So, I don't publish new version yet.

I shall publish it, after Atom v1.13.0 is released official.

---

変えたけど、v1.13.0はまだ正式版出てないから、出てから公開(apmでアップできるようにすること)します。

**Comment by nekonenene** [comment]
対応ありがとうございました！

**Comment by raccy** [comment]
v1.13.0で確認済み。
